script: "bundle exec rake travis"
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database nzffa_test;'
  - bundle exec rake db:schema:load
before_install:
  - gem update --system
  - gem --version
notifications:
  campfire: enspiral:f10283f8b70c9c73a0100bdfbfe8f71b7722a488@506651
