--- 
user: admin
group: admin
cwd: /home/admin/public_html/NZFFA.org.nz/current
log_file: log/mongrel.log
port: "3045"
environment: production
address: 127.0.0.1
pid_file: tmp/pids/dispatch.pid
servers: 2

